name: Build Base Images

on:
  push:
    branches:
      - master
      - devel

jobs:
  build_with_nvidia:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: detectron2
      ROS: noetic
      CUDA: 11.0-devel
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            ghcr.io/shunmo17/${{ env.IMAGE_NAME }}.nvidia:${{ env.ROS }}-cuda${{ env.CUDA }}
          build-args: |
            BASE_IMAGE=ghcr.io/shunmo17/ros1.nvidia:${{ env.ROS }}-cuda${{ env.CUDA }}
          file: ./Dockerfile
